cloud:
  aws:
    s3:
      bucket: i-likloud
    credentials:
      access_key: ENC(SvPTMWUFQWXza/cqCwq54F6n4FKEiQu0hWxJb3rjn4U=)
      secret_key: ENC(qgAoaOuYfYjyciBUvrasyc9e2wCZexEpQL3arPMPSARcfoazhL65J87kMU2ydZNri9563IwgtWs=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

spring:
  datasource:
  # 개인 aws 계정
    url: jdbc:mysql://43.200.97.214:3306/backend
    username: admin
    password: ENC(g8+MLR/TcWAhUpqNVPbh0Z5yy8EVyJbvFWTKQUu+5Go=)
  # 로컬 DB
#    url: jdbc:mysql://localhost:3306/backend
#    username: root
#    password: ENC(vS3bj58wnllM2lkJBVMecCaYDy2unUgl)